version: "3.8"
services:
  mongodb:
     container_name: mongo
     image: mongo:latest
     volumes:
      - /home/mongo_data:/data/db
      - ./data:/data  # Ensure the sample JSON file is accessible
     command: bash -c "if mongo wanderlust --eval 'db.posts.countDocuments()' --quiet | grep -q '^0$'; then mongoimport --db wanderlust --collection posts --file /data/sample_posts.json --jsonArray; fi"
     ports:
       - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5173:5173"

volumes:
  data:
