version: "3.8"
services:
  mongodb:
     container_name: mongo
     image: mongo:latest
     volumes:
       - /home/mongo_data:/data/db  # Store MongoDB data in /home/mongo_data on the host
       #- ./backend/data:/data
     ports:
       - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5173:5173"

volumes:
  data:
