version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data/db  # Ensure the data volume is accessible
    ports:
      - "27017:27017"
    command: ["/bin/bash", "-c", "/data/mongo-init.sh"]  # Use the init script to check and import
    volumes:
      - ./backend/data:/data  # Mount the folder containing both the DB and sample data

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5173:5173"

volumes:
  data:
